# 防火墙服务不能启动




## dynamic firewall daemon


```sh
[root@localhost ~]# systemctl start firewalld.service
Job for firewalld.service failed because the control process exited with error code. See "systemctl status firewalld.service" and "journalctl -xe" for details.
[root@localhost ~]# systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2021-03-04 09:25:53 CST; 13s ago
     Docs: man:firewalld(1)
  Process: 2140 ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS (code=exited, status=203/EXEC)
 Main PID: 2140 (code=exited, status=203/EXEC)

Mar 04 09:25:53 localhost.localdomain systemd[1]: Starting firewalld - dynamic firewall daemon...
Mar 04 09:25:53 localhost.localdomain systemd[1]: firewalld.service: main process exited, code=exited, status=203/EXEC
Mar 04 09:25:53 localhost.localdomain systemd[1]: Failed to start firewalld - dynamic firewall daemon.
Mar 04 09:25:53 localhost.localdomain systemd[1]: Unit firewalld.service entered failed state.
Mar 04 09:25:53 localhost.localdomain systemd[1]: firewalld.service failed.
[root@localhost ~]#
```



可能是由于系统里面安装的python版本原因。/usr/sbin/firewalld文件头部的python版本和安装的python版本不一致导致的。
1.先查看linux系统的Python版本
```sh
[root@localhost xinetd.d]# python --version
Python 2.7.5
```
查看firewalld在那个路径下
```sh
[root@localhost xinetd.d]# which firewalld
/usr/sbin/firewalld
```

查看firewalld文件和firewalld-cmd文件头是否一致且与Python一致，如果不一致，需要改成与Python版本一致。一般网上说是改成#!/usr/bin/python2.7 -Es，本机实验发现，都改成2也行。
```sh
[root@localhost xinetd.d]# head -n 10 /usr/sbin/firewalld
#!/usr/bin/python2 -Es
# -*- coding: utf-8 -*-
```
```sh
[root@localhost xinetd.d]# head -n 10  /usr/bin/firewall-cmd 
#!/usr/bin/python2 -Es
# -*- coding: utf-8 -*-
```

————————————————
版权声明：本文为CSDN博主「轩+1」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/qq_43524794/article/details/106741153



